const API_USER_URL = process.env.NEXT_PUBLIC_USER_API_URL;
const API_ADMIN_URL=process.env.NEXT_PUBLIC_ADMIN_API_URL;
const API_Owner_URL=process.env.NEXT_PUBLIC_OWNER_API_URL;

const API_AUTH_URL=process.env.NEXT_PUBLIC_USER_AUTH_API_URL;
const API_ADMIN_AUTH_URL=process.env.NEXT_PUBLIC_ADMIN_AUTH_API_URL;
const API_Owner_AUTH_URL=process.env.NEXT_PUBLIC_OWNER_AUTH_API_URL;


export { API_USER_URL,API_AUTH_URL,API_ADMIN_AUTH_URL,API_Owner_AUTH_URL,API_ADMIN_URL,API_Owner_URL }